# Generated by Django 4.2.3 on 2024-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genero',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
