# Generated by Django 4.2.3 on 2024-02-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('estacionamento', '0004_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='responsavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.userprofileexample'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.userprofileexample'),
        ),
    ]
