# Generated by Django 4.2.3 on 2024-02-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0005_pagamento_responsavel_veiculo_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='responsavel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estacionamento.dono'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estacionamento.dono'),
        ),
    ]
